# Generated by Django 5.1.3 on 2025-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_house_url_alter_house_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_ice_and_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
