# Generated by Django 5.1.3 on 2025-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_userbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='house',
        ),
        migrations.AddField(
            model_name='character',
            name='books',
            field=models.ManyToManyField(to='characters.book'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
