# Generated by Django 5.1.3 on 2025-01-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_character_house_character_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.house'),
        ),
    ]
