# Generated by Django 5.1.3 on 2025-01-05 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_book_date_score_delete_userbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
    ]
