# Generated by Django 5.1.3 on 2025-01-06 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_rename_score_rating_rename_score_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(0, 'No favorito'), (1, 'Me gusta'), (2, 'Guardado')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Puntuación'),
        ),
    ]
